// Generated by https://quicktype.io

export interface IOrders {
    id:            string;
    date:          string;
    user:          User;
    productsOrder: ProductsOrder[];
    orderDetail:   OrderDetail;
}

export interface OrderDetail {
    deliveryDate: string;
    totalPrice:   string;
    transactions: Transaction[];
}

export interface Transaction {
    status:    string;
    timestamp: string;
}

export interface ProductsOrder {
    cantidad: string;
    product:  Product;
}

export interface Product {
    id:          string;
    description: string;
    imgUrl:      string;
    price:       string;
    discount:    string;
}

export interface User {
    id: string;
}
