// Generated by https://quicktype.io

export interface IProductList {
    id:            string;
    article_id:    number;
    description:   string;
    imgUrl:        string;
    price:         string;
    stock:         number;
    discount:      string;
    averageRating: string;
    isAvailable:   boolean;
    isDeleted:     boolean;
    presentacion?: string; 
    tipoGrano?:    string;
    medida?:       string;
    category:      Category;
}

export interface Category {
    id:   string;
    name: string;
}

export interface IProductResponse {
   
    description:   string;
    imgUrl:        string;
    price:         string;
    stock:         number;
    discount:      string;
    presentacion?: string; 
    tipoGrano?:    string;
    medida?:       string;
    category:      Category;
}

export interface IProductErrorResponse {
   
    description:   string;
    imgUrl:        string;
    price:         string;
    stock:         number;
    discount:      string;
    presentacion?: string; 
    tipoGrano?:    string;
    medida?:       string;
    category:      Category;
}