import { IProduct } from "@/interfaces/IProduct";

export const products: IProduct[] = [
  {
    article_id: 1,
    description: "Café Molido Premium",
    url_img: "/cafe-Molida-Premium.png",
    price: 10.99,
    stock: 100,
    discount: 0,
    averageRating: 4.5,
    isAvailable: true,
    isDeleted: false,
    categoryId: 1,
  },
  {
    article_id: 2,
    description: "Café Molido Clásico",
    url_img: "/cafe-molido-clasico.webp",
    price: 9.99,
    stock: 150,
    discount: 0,
    averageRating: 4.0,
    isAvailable: true,
    isDeleted: false,
    categoryId: 1,
  },
  {
    article_id: 3,
    description: "Café en Granos Selecto",
    url_img: "/cafe-grano-selecto.webp",
    price: 12.99,
    stock: 80,
    discount: 0,
    averageRating: 4.7,
    isAvailable: true,
    isDeleted: false,
    categoryId: 2,
  },
  {
    article_id: 4,
    description: "Café en Granos Premium",
    url_img: "/cafe-grano-premium.webp",
    price: 13.99,
    stock: 70,
    discount: 0,
    averageRating: 4.8,
    isAvailable: true,
    isDeleted: false,
    categoryId: 2,
  },
  {
    article_id: 5,
    description: "Café en Cápsulas Intenso",
    url_img: "/cafe-capsulas-intenso.webp",
    price: 8.99,
    stock: 200,
    discount: 0,
    averageRating: 4.3,
    isAvailable: true,
    isDeleted: false,
    categoryId: 3,
  },
  {
    article_id: 6,
    description: "Café en Cápsulas Suave",
    url_img: "/cafe-capsulas-suave.webp",
    price: 7.99,
    stock: 120,
    discount: 0,
    averageRating: 4.1,
    isAvailable: true,
    isDeleted: false,
    categoryId: 3,
  },
  {
    article_id: 7,
    description: "Máquina de Café Expreso",
    url_img: "/maquina-expreso.webp",
    price: 199.99,
    stock: 30,
    discount: 0,
    averageRating: 4.9,
    isAvailable: true,
    isDeleted: false,
    categoryId: 4,
  },
  {
    article_id: 8,
    description: "Cafetera de Goteo",
    url_img: "/cafetera-goteo.webp",
    price: 59.99,
    stock: 50,
    discount: 0,
    averageRating: 4.2,
    isAvailable: true,
    isDeleted: false,
    categoryId: 4,
  },
  {
    article_id: 9,
    description: "Café Orgánico",
    url_img: "/cafe-organico.jpg",
    price: 14.99,
    stock: 90,
    discount: 0,
    averageRating: 4.6,
    isAvailable: true,
    isDeleted: false,
    categoryId: 1,
  },
  {
    article_id: 10,
    description: "Café Descafeinado",
    url_img: "/cafe-descafeinado.webp",
    price: 9.99,
    stock: 110,
    discount: 0,
    averageRating: 4.0,
    isAvailable: true,
    isDeleted: false,
    categoryId: 2,
  },
];

export const getProductsByCategory = (categoryId: number) => {
  return products.filter((product) => product.categoryId === categoryId);
};
